# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
import numpy as np

### 1 : Array Creation and Manipulation

In [3]:
# 1. Create 5x5 array of random integers between 1 and 20
arr = np.random.randint(1, 21, size=(5, 5))
print("Original Array: \n", arr)

# Replace all elements in the 3rd column (index 2) with 1
arr[:, 2] = 1
print("Modified Array: \n", arr)

Original Array: 
 [[ 7  7  7 20  2]
 [20 20 16 13  1]
 [19  7 19 15 15]
 [ 2  9 14  2 12]
 [13 10 13  4 16]]
Modified Array: 
 [[ 7  7  1 20  2]
 [20 20  1 13  1]
 [19  7  1 15 15]
 [ 2  9  1  2 12]
 [13 10  1  4 16]]


In [4]:
arr = np.arange(1, 17).reshape(4, 4)
print("Original Array: \n", arr)

np.fill_diagonal(arr, 0)
print("Array after setting diagonal to 0: \n", arr)

Original Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Array after setting diagonal to 0: 
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### 2 : Array Indexing and Slicing

In [5]:
arr = np.arange(1, 37).reshape(6, 6)
print("Original Array: \n", arr)

sub_arr = arr[2 : 5, 1 : 4]
print("Sub-array (3rd–5th rows, 2nd–4th cols):\n", sub_arr)

Original Array: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array (3rd–5th rows, 2nd–4th cols):
 [[14 15 16]
 [20 21 22]
 [26 27 28]]


In [7]:
# Create a NumPy array of shape (5, 5) with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Extract the elements on the border
# Extract border elements of a 2D array by combining:
border_elements = np.concatenate((
    array[0, :],        # First row (all columns) → top border
    array[-1, :],       # Last row (all columns) → bottom border
    array[1:-1, 0],     # First column (excluding top & bottom already taken).  This gives elements from rows 1 to second-last row, column 0 → left border (middle part)
    array[1:-1, -1] # Last column (excluding top & bottom). This gives elements from rows 1 to second-last row, last column → right border (middle part)
))
# np.concatenate() joins all these parts into a single 1D array.

print("Border elements:")
print(border_elements)

Original array:
[[12  6 17  6 12]
 [ 3  9 17  2 16]
 [ 3 10  1  5 14]
 [ 9 11 12  9 18]
 [ 5  9 18  3  5]]
Border elements:
[12  6 17  6 12  5  9 18  3  5  3  3  9 16 14 18]


### 3: Array Operations

In [8]:
a = np.random.randint(1, 10, size = (3,4))
b = np.random.randint(1, 10, size = (3,4))

print("Array a:\n", a)
print("Array b:\n", b)

add = a + b
sub = a - b
mul = a * b
div = a / b

print("Addition:\n", add)
print("Subtraction:\n", sub)
print("Multiplication:\n", mul)
print("Division:\n", div)

Array a:
 [[9 9 9 7]
 [6 2 7 3]
 [9 4 5 6]]
Array b:
 [[6 7 3 4]
 [3 7 6 2]
 [9 2 2 6]]
Addition:
 [[15 16 12 11]
 [ 9  9 13  5]
 [18  6  7 12]]
Subtraction:
 [[ 3  2  6  3]
 [ 3 -5  1  1]
 [ 0  2  3  0]]
Multiplication:
 [[54 63 27 28]
 [18 14 42  6]
 [81  8 10 36]]
Division:
 [[1.5        1.28571429 3.         1.75      ]
 [2.         0.28571429 1.16666667 1.5       ]
 [1.         2.         2.5        1.        ]]


In [10]:
# Row-wise and column-wise sum of 4×4 array

arr = np.arange(1, 17).reshape(4, 4)
print("Original Array: \n", arr)

row_sum = arr.sum(axis = 1)
col_sum = arr.sum(axis = 0)

print("Row-wise sum: ", row_sum)
print("Col-wise sum: ", col_sum)

Original Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:  [10 26 42 58]
Col-wise sum:  [28 32 36 40]


### 4: Statistical Operations

In [ ]:
# Mean, median, std, variance

arr = np.random.randint(1, 100, size = (5, 5))
print("Array:\n", arr)

mean_val = np.mean(arr)
median_val = np.median(arr)
std_val = np.std(arr)
var_val = np.var(arr)

print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)
print("Variance:", var_val)

Array:
 [[41 41 13 78 19]
 [68 31 56  7 26]
 [24 34 29 40 79]
 [98 64 88 11 13]
 [19 28 48 63 35]]
Mean: 42.12
Median: 35.0
Standard Deviation: 25.187806573816626
Variance: 634.4256


In [13]:
# Normalize 3×3 array (mean 0, std 1)

arr = np.arange(1, 10).reshape(3, 3)
print("Original Array:\n", arr)

mean_val = np.mean(arr)
std_val = np.std(arr)

normalized_arr = (arr - mean_val) / std_val
print("Normalized Array:\n", normalized_arr)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Array:
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### 5: Broadcasting

In [14]:
# Add 1D array (3,) to each row of 3×3

arr = np.random.randint(1, 10, size = (3, 3))
row_add = np.array([1, 2, 3])

print("Original Array:\n", arr)
print("1D Array to add:\n", row_add)

res = arr + row_add
print("Resultant Array after addition:\n", res)

Original Array:
 [[5 8 7]
 [5 2 6]
 [7 9 9]]
1D Array to add:
 [1 2 3]
Resultant Array after addition:
 [[ 6 10 10]
 [ 6  4  9]
 [ 8 11 12]]


In [16]:
arr = np.random.randint(1, 20, size = (4, 4))
col_vec = np.array([1,2,3,4]) # Shape (4,)

print("Array: \n", arr)
print("Column Vector: \n", col_vec)

# Make it a column vector of shape (4,1), then broadcast across columns
res = arr + col_vec[:, np.newaxis]
print("Resultant Array after adding column vector: \n", res)

Array: 
 [[ 9 18 12  4]
 [16  5 14 18]
 [ 3 10 10  4]
 [ 2 15  2 10]]
Column Vector: 
 [1 2 3 4]
Resultant Array after adding column vector: 
 [[10 19 13  5]
 [18  7 16 20]
 [ 6 13 13  7]
 [ 6 19  6 14]]


### 6: Linear Algebra

In [17]:
# Determinant, inverse, eigenvalues of a 3×3 matrix

a = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

print("Matrix:\n", a)

det = np.linalg.det(a)
inv = np.linalg.inv(a)
eigenvalues, eigenvectors = np.linalg.eig(a)

print("Determinant:", det)
print("Inverse:\n", inv)
print("Eigenvalues:", eigenvalues)

Matrix:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]
Determinant: 0.9999999999999964
Inverse:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
Eigenvalues: [-5.2296696  -0.02635282  7.25602242]


In [18]:
# Matrix multiplication of shapes (2,3) and (3,2)

arr1 = np.random.randint(1, 11, size=(2, 3))
arr2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:", arr1)
print("Array 2:", arr2)

# Perform matrix multiplication
result = np.dot(arr1, arr2)
print("Matrix multiplication result:")
print(result)

Array 1: [[9 1 7]
 [5 4 6]]
Array 2: [[5 3]
 [8 3]
 [5 3]]
Matrix multiplication result:
[[88 51]
 [87 45]]


### 7: Advanced Array Manipulation

In [20]:
arr = np.arange(1, 10).reshape(3, 3)
print("Original Array:\n", arr)

arr_1x9 = arr.reshape(1, 9)
print("Reshaped Array (1,9):\n", arr_1x9)

arr_9x1 = arr.reshape(9, 1)
print("Reshaped Array (9,1):\n", arr_9x1)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped Array (1,9):
 [[1 2 3 4 5 6 7 8 9]]
Reshaped Array (9,1):
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [21]:
arr = np.random.randint(1, 100, size=(5, 5))
print("Array:\n", arr)

flat = arr.flatten()
print("Flattened Array:\n", flat)

reshaped = flat.reshape(5, 5)
print("Reshaped back to (5,5):\n", reshaped)

Array:
 [[15 19 55 91 35]
 [69 30 13 30  9]
 [68 33 65 69 48]
 [13 22 84 71 44]
 [42 31 88 44 14]]
Flattened Array:
 [15 19 55 91 35 69 30 13 30  9 68 33 65 69 48 13 22 84 71 44 42 31 88 44
 14]
Reshaped back to (5,5):
 [[15 19 55 91 35]
 [69 30 13 30  9]
 [68 33 65 69 48]
 [13 22 84 71 44]
 [42 31 88 44 14]]


### 8: Fancy Indexing and Boolean Indexing

In [22]:
# Fancy indexing to get corner elements

arr = np.random.randint(1, 100, size=(5, 5))
print("Array:\n", arr)

# Corners: (0,0), (0,-1), (-1,0), (-1,-1)
corners = arr[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:", corners)

Array:
 [[87 30  2 52 47]
 [42 94 40 32 12]
 [47 34 64  1 16]
 [ 2 39 95 91 89]
 [19 58  5 24 23]]
Corner elements: [87 47 19 23]


In [23]:
# Boolean indexing: set elements > 10 to 10

arr = np.random.randint(1, 20, size=(4, 4))
print("Original Array:\n", arr)

arr[arr > 10] = 10
print("After capping elements > 10 to 10:\n", arr)

Original Array:
 [[ 6 15  7 15]
 [15 14  8  4]
 [12 18 16 16]
 [ 5 10 13 14]]
After capping elements > 10 to 10:
 [[ 6 10  7 10]
 [10 10  8  4]
 [10 10 10 10]
 [ 5 10 10 10]]


### 9: Structured Arrays

In [24]:
# Structured array with name, age, weight and sort by age

dtype_person = np.dtype([
    ('name', 'U20'),
    ('age', 'i4'),
    ('weight', 'f4')
])

people = np.array([
    ('Rohan', 21, 65.5),
    ('Aditi', 19, 55.2),
    ('Vikas', 23, 70.0),
    ('Neha', 20, 50.0)
], dtype=dtype_person)

print("Original structured array:\n", people)

# Sort by age
sorted_people = np.sort(people, order='age')
print("Sorted by age:\n", sorted_people)


Original structured array:
 [('Rohan', 21, 65.5) ('Aditi', 19, 55.2) ('Vikas', 23, 70. )
 ('Neha', 20, 50. )]
Sorted by age:
 [('Aditi', 19, 55.2) ('Neha', 20, 50. ) ('Rohan', 21, 65.5)
 ('Vikas', 23, 70. )]


In [25]:
# Structured array with x, y and pairwise Euclidean distance

# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
# Here 'i4' means 4-byte integer. We are defining two columns: x and y.

data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
# Creating a structured array with 3 points:
# Point 1 → (1, 2)
# Point 2 → (3, 4)
# Point 3 → (5, 6)
# Each point has fields 'x' and 'y'.

print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
# Formula:  √((x1 - x2)² + (y1 - y2)²)

distances = np.sqrt(
    # (x1 - x2)²
    (data['x'][:, np.newaxis] - data['x'])**2
    # data['x'] gives array of all x-values → [1, 3, 5]
    # data['x'][:, np.newaxis] converts it to a column → [[1], [3], [5]]
    # Subtracting gives pairwise differences between each x-value.
    +
    # (y1 - y2)²
    (data['y'][:, np.newaxis] - data['y'])**2
    # Same idea for y-values: pairwise differences for y
)

print("Euclidean distances:", distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances: [[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### 10: Masked Arrays

In [26]:
# Mask elements > 10 and sum unmasked

import numpy.ma as ma  # Import masked array module

arr = np.random.randint(1, 20, size=(4, 4))  
print("Original array:\n", arr)

# Mask (hide) all values greater than 10
masked_arr = ma.masked_greater(arr, 10)
print("Masked array (values > 10 are masked):\n", masked_arr)

# Sum only the unmasked (visible) values
sum_unmasked = masked_arr.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
 [[15  4 19 16]
 [18 12  3 14]
 [15 18  4 18]
 [ 4  9 17 10]]
Masked array (values > 10 are masked):
 [[-- 4 -- --]
 [-- -- 3 --]
 [-- -- 4 --]
 [4 9 -- 10]]
Sum of unmasked elements: 34


In [27]:
# Mask diagonal elements and replace with mean of unmasked

import numpy.ma as ma  # Import masked array module

arr = np.random.randint(1, 20, size=(3, 3))
print("Original array:\n", arr)

# Create a mask for diagonal elements (True on diagonal)
diag_mask = np.eye(3, dtype=bool)

# Apply the mask → diagonal values become hidden
masked_arr = ma.array(arr, mask=diag_mask)
print("Masked array (diagonal masked):\n", masked_arr)

# Calculate mean of only unmasked (non-diagonal) elements
mean_unmasked = masked_arr.mean()
print("Mean of unmasked elements:", mean_unmasked)

# Fill masked (diagonal) positions with the computed mean
filled_arr = masked_arr.filled(mean_unmasked)
print("Final array with diagonal replaced by mean:\n", filled_arr)

Original array:
 [[12 12  6]
 [ 6  1 12]
 [14  4 13]]
Masked array (diagonal masked):
 [[-- 12 6]
 [6 -- 12]
 [14 4 --]]
Mean of unmasked elements: 9.0
Final array with diagonal replaced by mean:
 [[ 9 12  6]
 [ 6  9 12]
 [14  4  9]]
