NumPy is a fundamental library for scientific computing in Python.
It provides support for arrays and matrices, along with collection of mathematical functions to operate on these structures.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
# 2D array

arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [ ]:
np.arange(0,10,2).reshape(5,1)  # start, end, step

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,4))  # 3 rows and 4 columns of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
## Identity matrix

np.eye(4)  # 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Attributes of NumPy arrays

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Data Type:", arr.dtype)
print("Size:", arr.size)
print("Item Size (in bytes):", arr.itemsize)
print("Total Bytes:", arr.nbytes)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Data Type: int64
Size: 9
Item Size (in bytes): 8
Total Bytes: 72


In [16]:
# NumPy Vectorized Operations

arr4 = np.array([1,2,3,4,5])
arr5 = np.array([10,20,30,40,50])

# Element-wise addition
print("Addition:", arr4 + arr5)

# Element-wise subtraction
print("Subtraction:", arr5 - arr4)

# Element-wise multiplication
print("Multiplication:", arr4 * arr5)

# Element-wise division
print("Division:", arr5 / arr4)

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]


In [17]:
# Universal Functions (ufuncs) in NumPy

arr6 = np.array([2,3,4,5,6])
# Square root
print("Square Root:", np.sqrt(arr6))

# Exponential
print("Exponential:", np.exp(arr6))

# Sine
print("Sine:", np.sin(arr6))

# Natural Logarithm
print("Natural Logarithm:", np.log(arr6))

Square Root: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential: [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sine: [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Natural Logarithm: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [19]:
# Slicing and Indexing in NumPy Arrays

arr7 = np.array([[10,20,30,40,50], [60,70,80,90,100], [110,120,130,140,150]])
print("Original Array:\n", arr7)

Original Array:
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]


In [27]:
print(arr7[0][0])
print(arr7[0:2, 1:])

10
[[ 20  30  40  50]
 [ 70  80  90 100]]


In [28]:
print(arr7[1:, 1:3])

[[ 70  80]
 [120 130]]


In [25]:
print(arr7[1:, 2:])

[[ 80  90 100]
 [130 140 150]]


In [29]:
# Modify elements
arr7[0,0] = 200
print("Modified Array:\n", arr7)

Modified Array:
 [[200  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]


In [32]:
arr7[1:] = 300
print(arr7)

[[200  20  30  40  50]
 [300 300 300 300 300]
 [300 300 300 300 300]]


In [34]:
# Statistical Operations with NumPy - Normalization
# To have a mean of 0 and standard deviation of 1

# Calculate mean and standard deviation
mean = np.mean(arr7)
std_dev = np.std(arr7)

# Normalize the array
normalized_arr = (arr7 - mean) / std_dev
print("Normalized Array:\n", normalized_arr)

Normalized Array:
 [[-0.19547333 -1.74776156 -1.66152332 -1.57528509 -1.48904685]
 [ 0.66690901  0.66690901  0.66690901  0.66690901  0.66690901]
 [ 0.66690901  0.66690901  0.66690901  0.66690901  0.66690901]]


In [35]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [37]:
# Logical Operations

data = np.array([10, 15, 20, 25, 30])

data[(data > 20) & (data < 30)]  # This will raise an error

array([25])